#ifndef INCLUDED_SDK_DEFINITIONS_H
#define INCLUDED_SDK_DEFINITIONS_H

#ifndef SDK_SIZEOF_VOID_P
#define SDK_SIZEOF_VOID_P 4
#endif

#ifndef SDK_ALIGN_SIZE
#define SDK_ALIGN_SIZE (SDK_SIZEOF_VOID_P*2)
#endif


#endif /*INCLUDED_SDK_DEFINITIONS_H*/
