#ifndef INCLUDED_SDK_DEFINITIONS_H
#define INCLUDED_SDK_DEFINITIONS_H

#ifndef SDK_SIZEOF_VOID_P
#define SDK_SIZEOF_VOID_P 4
#endif

#ifndef SDK_ALIGN_SIZE
#define SDK_ALIGN_SIZE (SDK_SIZEOF_VOID_P*2)
#endif

#ifndef SDK_USE_TLSF
    #define SDK_USE_TLSF 1
#endif

#ifndef SDK_TLSF_MEMORY_POOL_SIZE
    #define SDK_TLSF_MEMORY_POOL_SIZE (1024*1024*1024)
#endif

#ifndef SDK_PRINTF_BUFFER_SIZE
    #define SDK_PRINTF_BUFFER_SIZE 1024
#endif

#endif /*INCLUDED_SDK_DEFINITIONS_H*/
